In [12]:
# Food Delivery Data Analysis
#Internship Assignment

In [ ]:
from google.colab import files
files.upload()

In [ ]:
import os
os.listdir()

In [ ]:
import pandas as pd
import sqlite3

In [ ]:
orders = pd.read_csv("orders.csv")
users = pd.read_json("users.json")

conn = sqlite3.connect("restaurants.db")
restaurants = pd.read_sql("SELECT * FROM restaurants", conn)

In [15]:
import sqlite3

conn = sqlite3.connect("restaurants.db")
cursor = conn.cursor()

with open("restaurants (1).sql", "r") as file:
    cursor.executescript(file.read())

conn.commit()

In [16]:
import pandas as pd

restaurants = pd.read_sql("SELECT * FROM restaurants", conn)
restaurants.head()

   restaurant_id restaurant_name  cuisine  rating
0              1    Restaurant_1  Chinese     4.8
1              2    Restaurant_2   Indian     4.1
2              3    Restaurant_3  Mexican     4.3
3              4    Restaurant_4  Chinese     4.1
4              5    Restaurant_5  Chinese     4.8

In [17]:
orders = pd.read_csv("orders.csv")
users = pd.read_json("users.json")

In [18]:
df = orders.merge(users, on="user_id", how="left")
df = df.merge(restaurants, on="restaurant_id", how="left")

In [20]:
df.shape

(10000, 12)

In [19]:
# Gold member orders
gold_orders = df[df["membership"] == "Gold"]

# Revenue by city
df.groupby("city")["total_amount"].sum()

# Cuisine-wise average order value
df.groupby("cuisine")["total_amount"].mean()

cuisine
Chinese    798.389020
Indian     798.466011
Italian    799.448578
Mexican    808.021344
Name: total_amount, dtype: float64